version: "3.7"
services:
  app:
    build:
      args:
        user: "migueljbarbosa2001@gmail.com"
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: "project-image"
    container_name: "project"
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - "project"
  db:
    image: mysql:8.0
    container_name: "projectDB"
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - "project"
  nginx:
    image: nginx:alpine
    container_name: "projectNGINX"
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - "project"
networks:
  "project":
    driver: bridge